### ISSUE TITLE
Fix connection to Arches Collector mobile

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#153] opened 2020-05-28 18:46 UTC
@coherit has done a ton of work to move this issue very far along (see #85), but we are still having trouble syncing data. This ticket is to track that work and the solution to it.

**Comment by coherit** [comment] 2020-06-04 18:17
There are three sub-issues related to this ticket:

1.  Authentication errors preventing project connection and syncing = FIXED
2.  Dates being passed from the collector as full UTC datetimes see (https://github.com/archesproject/arches/issues/6043) = FIXED
3.  Photos uploaded via the Collector get named 1.jpg, causing all subsequent collector scout reports to show the same photo on the file system (although not immediately) = BROKEN

1 was because couchdb was updated to 3.1.0 on the server; uninstalling and installing 2.3.1 fixed this; (originally this was due to some custom overrides to auth/ that was already fixed in the prior ticket)

2 required a new function, process_mobile_dates be added to the DateDataType class in datatypes.py. The function strips timezone and time data, returning a date. Additional logic had to be added to the existing date validate function in datatypes.py to similarly handle the UTC datetime being passed by Collector (it validates on a full datetime rather than stripping down to the date). Fixed in latest commit on the legiongis fork of arches origin/stable/5.0.x-fpan-dateparse

3 is at least partially a problem with some of the S3 setup -- the current error on file upload is:
 ModuleNotFoundError: No module named 'storages'

**Comment by coherit** [comment] 2020-06-04 18:56
Addressed 3 partially by installing two missing modules:
pip install django-storages 
pip install boto3 

Now testing file uploads... here's how to reproduce the problem:
1. Submit a scout report with photo from your phone through the collector
2. Sync the project to upload to server
Result:
![image](https://user-images.githubusercontent.com/3217017/83798516-5faedf80-a672-11ea-8857-ba771962003d.png)
3. Add another scout report using a photo from your phone
4. Sync the project to upload to server

The new image uploaded on the second report will replace the image uploaded on the first report. This is because the collector defaults to naming photos "1.jpg" -- and when it's synced to the server, it overwrites the previously uploaded "1.jpg"
So, the original resource report now looks like:
![image](https://user-images.githubusercontent.com/3217017/83799214-7a358880-a673-11ea-8b9d-a1f81cf4a26d.png)

That is the original scout report with the photo of the second report.

**Comment by mradamcox** [comment] 2020-06-04 20:06
@coherit If I'm understanding this image naming project, I'd say this seems worthy of a new ticket in the core Arches repo, or at least a forum post to see if others have encountered the same thing.

**Comment by coherit** [comment] 2020-06-04 20:31
had to do a bit more work on the date parsing to handle cases where phones aren't passing localized timezone data (neil's phone right now). Tested against 3 phones: iphone 11, samsung galaxy 7, and pixel 3. Should handle phones that pass dates in Y-M-D format as well as full UTC, which are the two cases I've encountered so far.

**Comment by coherit** [comment] 2020-06-05 17:33
@mradamcox I've posted to the forum for issue 3 above. Once you enable ssl, I'll test the collector connection again.

**Comment by mradamcox** [comment] 2020-06-05 17:38
Ok great. That seems like a good plan. Won't be til next week at least
though.

**Comment by coherit** [comment] 2021-01-11 18:50
Closing this issue to track in new Arches 5.1 version in issue #178

**Closed as completed by coherit** 2021-01-11 18:50 UTC
Labels: bug
